### ISSUE TITLE
What is living at the API_URL?

### ISSUE THREAD

**Issue by ralyodio** [Phantom8015/stable-diffusion-es#1]
`API_URL = "wss://runwayml-stable-diffusion-v1-5.hf.space/queue/join"`

What is this? And how do I run one myself?

**Comment by Phantom8015** [comment]
Pretty sure you can use this: https://runwayml.com/hosted-models/. I found this API online so not sure.

**Comment by Phantom8015** [comment]
May I mark this issue as closed?
